spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/inventorydb}
      database: inventorydb
      auto-index-creation: true
  
server:
  port: 8080
  servlet:
    context-path: /api

cors:
  allowed-origins: https://smart-inventory-management-frontend.vercel.app/

ml-service:
  url: https://smart-inventory-management-ml.onrender.com
  api-key: ${ML_API_KEY}